#ifndef __PLATFORM_APP_CFG_H__
#define __PLATFORM_APP_CFG_H__

#include "vsf.h"

#define VSF_USE_FUNCTION_KEY ENABLED
#define CONSOLE_BUFFER_SIZE 50

#define SUPPORT_CONSOLE_DEFAULT_CMD_EX_EN

#endif
