#ifndef __PLATFORM_APP_CFG_H__
#define __PLATFORM_APP_CFG_H__

#include "vsf.h"

#define VSF_USE_FUNCTION_KEY ENABLED
#define CONSOLE_INPUT_SIZE 10
#define CONSOLE_BUFFER_SIZE 50

#define SUPPORT_CONSOLE_DEFAULT_CMD_EX_EN

#define VSF_USE_KEY_FILTER ENABLED

#define IS_KEY1_DOWN()  (GPIO_PIN_RESET == HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_5))
#define IS_KEY1_UP()    (GPIO_PIN_SET == HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_5))

#endif
